package com.example.pfe.entities;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;

@Entity
@Table(name = "leave_documents", indexes = {
        @Index(name = "idx_ld_user_id",          columnList = "user_id"),
        @Index(name = "idx_ld_leave_request_id",  columnList = "leave_request_id"),
        @Index(name = "idx_ld_document_type",     columnList = "document_type"),
        @Index(name = "idx_ld_status",            columnList = "status")
})
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
public class LeaveDocument {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // ─── Relations ────────────────────────────────────────────
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "leave_request_id", nullable = false)
    private LeaveRequest leaveRequest;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;                  // the employee who owns the document

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "uploaded_by")
    private User uploadedBy;            // null if generated by system

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "reviewed_by")
    private User reviewedBy;            // admin who reviewed

    // ─── File metadata ────────────────────────────────────────
    @Enumerated(EnumType.STRING)
    @Column(name = "document_type")
    private DocumentType documentType;

    @Enumerated(EnumType.STRING)
    @Column(name = "document_category", nullable = false)
    private DocumentCategory documentCategory;  // GENERATED or UPLOADED

    @Column(name = "file_name", nullable = false, length = 255)
    private String fileName;            // e.g. "42_acceptation_letter.pdf"

    @Column(name = "file_path", nullable = false, length = 500)
    private String filePath;
    // e.g. "uploads/leaves/7/authorizations/42_acceptation_letter.pdf"

    @Column(name = "file_size")
    private Long fileSize;              // bytes

    @Column(name = "mime_type", length = 100)
    private String mimeType;

    // ─── Status ───────────────────────────────────────────────
    @Enumerated(EnumType.STRING)
    @Builder.Default
    private DocumentStatus status = DocumentStatus.APPROVED;

    // ─── Generation metadata ──────────────────────────────────
    @Column(name = "generated_by_system")
    @Builder.Default
    private Boolean generatedBySystem = false;

    @Column(name = "generated_at")
    private LocalDateTime generatedAt;

    // ─── Review metadata ──────────────────────────────────────
    @Column(name = "admin_notes", columnDefinition = "TEXT")
    private String adminNotes;

    @Column(name = "reviewed_at")
    private LocalDateTime reviewedAt;

    // ─── Timestamps ───────────────────────────────────────────
    @Column(name = "uploaded_at")
    private LocalDateTime uploadedAt;

    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    // ─── Enums ────────────────────────────────────────────────

    public enum DocumentType {
        ACCEPTATION_LETTER,     // generated when leave is APPROVED
        JUSTIFICATION,          // auto-generated justification letter
        MEDICAL_CERTIFICATE,    // uploaded by employee
        PROOF,                  // other supporting document (uploaded)
        OTHER
    }

    public enum DocumentCategory {
        GENERATED,  // produced automatically by the system
        UPLOADED    // manually uploaded by employee or admin
    }

    public enum DocumentStatus {
        PENDING,
        APPROVED,
        REJECTED,
        ARCHIVED
    }
}