# Dev local uniquement
spring.datasource.url=jdbc:mysql://localhost:3306/pfe?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
app.frontend.url=http://localhost:4200
app.base-url=http://localhost:8080
server.port=8080
app.jwt.secret=NSI88IzYFdGzL1tO+Lzk3pVDg89tut7r38K9vwHXx28=
spring.mail.username=oumawerf12@gmail.com
spring.mail.password=ufqu rhtg cjbr wmlw
groq.api.key=${GROQ_API_KEY}
spring.datasource.hikari.leak-detection-threshold=2000
spring.datasource.hikari.connection-timeout=5000
logging.level.com.zaxxer.hikari=DEBUG
logging.level.com.zaxxer.hikari.HikariPool=DEBUG
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
app.upload.dir=uploads/leave-documents
langchain4j.ollama.base-url=http://localhost:11434
langchain4j.ollama.chat-model.model-name=mistral
langchain4j.ollama.chat-model.temperature=0.7
langchain4j.ollama.embedding-model.model-name=nomic-embed-text
langchain4j.chroma.url=http://localhost:8000
langchain4j.chroma.collection-name=pdf-documents