# Dev local uniquement - surcharges légères
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
logging.level.com.zaxxer.hikari=DEBUG
logging.level.com.zaxxer.hikari.HikariPool=DEBUG